### ISSUE TITLE
When clicked once, the story does not open in the simulator.

### ISSUE THREAD

**Issue by jbjeong-kosac** [orta/vscode-react-native-storybooks#34]
hello, I have a problem.

# The Problem:
  - When clicked once, the story does not open in the simulator.

# Env
  - React Native Storybook Vscode Extensions Version: 2.7.0
  - @Stroybook 버전: 5.2.1
  - VSCode Version: 1.38.1
  - Connected to stories(show the stories)
  - When clicked once, the story does not open in the simulator. (it is working, good) 

How can I solve this problem?

**Comment by jb9229** [comment]
@Manishalexin 

Unfortunately, I haven't solved this problem yet.

Why didn't change the stories in emulator when click the story at VSCode? Could you help?

# Env Info
  • [Issue Video](https://drive.google.com/file/d/1cnduyBdDuIv3urTtIzsbspycXmpbksi2/view?usp=sharing)
  • React Native Storybook extension of VSCode: 2.7.0
  • Storybook package version: 5.2.7
  • Web stories work well, only VSCode stories is not working(but changed selected source)

I want to use VSCode stories to change the story, how can I solve the problem?

**Comment by Manishalexin** [comment]
@jb9229 It was published just that the version is somehow not incremented to the latest. So the fix is available in 2.6.1. I will create a PR with some more fixes so everything can be brought to the latest. Till then, use the 2.6.1 ( install other version option in VS Code plugins list ).

**Comment by ZenBoat** [comment]
Please release the small change as a patch change (2.7.1). The reason most people install this extension is for the simulator link. The latest version still does not work.

**Comment by jb9229** [comment]
@ZenBoat Are there any other reasons not to use 2.6.1?
I have no big problem with that version yet

**Comment by ZenBoat** [comment]
No, 2.6.1 is working fine. 

But new users will not install an older version; they would install 2.7.0, that is the version vscode would install. With the interest of not wasting new users time, the latest version should be working.

**Comment by orta** [comment]
Thanks folks - I' ve shipped 2.7.1 👍
